
modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="mekaradio"
version="${file.jarVersion}"
displayName="Mekanism Radioactive"
authors="FixedDolphin927"
description="An Addon of Mekanism"
[[dependencies.mekaradio]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekaradio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
